[package]
name = "sanguine"
version = "0.1.0-dev-r2"
edition = "2021"
authors = ["Will Hopkins <willothyh@gmail.com"]
description = "A library for creating dynamic TUI experiences in Rust"
repository = "https://github.com/willothy/sanguine"
license = "MIT"
readme = "README.md"
keywords = ["tui", "terminal", "user-interface"]
categories = ["gui", "command-line-interface"]

[dependencies]
anyhow = "1.0.70"
ctrlc = "3.2.5"
itertools = "0.10.5"
rand = "0.8.5"
slotmap = "1.0.6"
termwiz = { version = "0.20.0", features = ["serde"] }
