[package]
name = "red-tui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.70"
itertools = "0.10.5"
termwiz = { version = "0.20.0", features = ["serde"] }
