[package]
name = "sanguine"
version = "0.1.0"
edition = "2021"
authors = ["Will Hopkins <willothyh@gmail.com"]
description = "A library for creating dynamic TUI experiences in Rust"
repository = "https://github.com/willothy/sanguine"
license = "MIT"
readme = "README.md"
keywords = ["tui", "terminal", "user-interface"]
categories = ["tui", "terminal", "user-interface"]

[dependencies]
anyhow = "1.0.70"
itertools = "0.10.5"
termwiz = { version = "0.20.0", features = ["serde"] }
