[package]
name = "sanguine"
version = "0.2.0"
edition = "2021"
authors = ["Will Hopkins <willothyh@gmail.com>"]
description = "A library for creating dynamic TUI experiences in Rust"
repository = "https://github.com/willothy/sanguine"
license = "MIT"
readme = "README.md"
keywords = ["tui", "terminal", "user-interface"]
categories = ["gui", "command-line-interface"]

[dependencies]
slotmap = "1.0.6"
termwiz = "0.20.0"
thiserror = "1.0.40"
